project:
  type: website
  render: 
   - index.qmd
   - courses.qmd
   - "Getting-Started/*"
   - "Example-Notebooks/*"


website:
  title: "Training Resources"
  repo-url: https://github.com/NCI900-Training-Organisation/learning-resources.git
  repo-actions: [edit, source, issue]
  reader-mode: true
  navbar:
    logo: img/NCI logo White small.png
    background: "#324159"
    search: true
    # left:
      # - href: index.qmd
      #   text: Home
      # - href: courses.qmd
      #   text: Courses
      # - href: tutorials.qmd
      #   text: Tutorials
      # - text: "More"
      #   menu:
      #     - about.qmd 
    tools:
      - icon: github
        href: https://github.com/orgs/NCI900-Training-Organisation/repositories
  sidebar:
    style: "floating"
    search: true
    contents: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



